### PR TITLE
Random database password

### PR DESCRIPTION
**Pull request by paragonie-scott**
See #84

### CODE REVIEW

**Comment by paragonie-scott** [comment]
@kelunik @co60ca If either of you could confirm that this works as expected, I'd greatly appreciate it.

**Comment by co60ca** [comment]
Will do it before tomorrow.

**Comment by co60ca** [comment]
Lucky me, I fucked it up

**Comment by co60ca** [comment]
```
database_1 | 
database_1 | 
database_1 | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sh
database_1 | /docker-entrypoint-initdb.d/init.sh: line 3: php: command not found
```

**Comment by paragonie-scott** [comment]
> Additionally we are missing most of the files from docker/psql. And random_password.php wont work either since we're not copying your ConstantTime libraries in there

Hahaha oops.

**Comment by co60ca** [comment]
You should learn docker sometime, the setup process is checkpointed so you don't have to rebuild unless something changed along the way.

**Comment by paragonie-scott** [comment]
I think this is obsoleted by the closing of #57 :)

**Comment by kelunik** [comment]
Only if we move postgres back into the same container. Currently, they're two different containers.

**Comment by co60ca** [comment]
Perhaps we can provide two options, some may prefer them to be bundled, perhaps as an intro to the system

**Pull request closed without merging**
